export const RESERVE = 'RESERVE'
export const GET_RESERVATIONS = 'GET_RESERVATIONS'
export const GET_FILTERED_RESERVATIONS = 'GET_FILTERED_RESERVATIONS'
export const DELETE_RESERVATION = 'DELETE_RESERVATION'
export const UPDATE_RESERVATION = 'UPDATE_RESERVATION'

export const GET_ERROR = 'GET_ERROR'
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
